# Generated by Django 2.0.9 on 2018-10-09 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LoginLogoutLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('last_logout_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('total_online_time', models.DurationField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('which_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Standard')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(max_length=400)),
                ('which_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Chapter')),
                ('which_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Standard')),
                ('which_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='which_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Standard'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='which_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Subject'),
        ),
    ]
