# Generated by Django 2.0.9 on 2018-10-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='video',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
